import logging
import math

import torch
from torch import Tensor
from torch import nn
import torch.nn.functional as F  # noqa: N812
from transformers.cache_utils import DynamicCache

import openpi.models.gemma as _gemma
from openpi.models_pytorch.pi0_pytorch import create_sinusoidal_pos_embedding
from openpi.models_pytorch.pi0_pytorch import sample_beta
import openpi.models_pytorch.preprocessing_pytorch as _preprocessing
from openpi.models_pytorch.ftp1_attention_masks import build_action_denoise_layout
from openpi.models_pytorch.ftp1_attention_masks import build_expert_attention_layout
from openpi.models_pytorch.ftp1_attention_masks import build_prefix_attention_layout
from openpi.models_pytorch.ftp1_attention_masks import build_tactile_attention_layout
from openpi.models_pytorch.ftp1_blocks import FourierStateEncoder
from openpi.models_pytorch.ftp1_blocks import FTP1HptTactileEncoder
from openpi.models_pytorch.ftp1_gemma_pytorch import FTP1PaliGemmaWithExpertModel
from openpi.models_pytorch.ftp1_model_config import FTP1ModelConfig


class FTP1Pytorch(nn.Module):
    def __init__(self, config: FTP1ModelConfig):
        # Updation from Pi0Pytorch:
        # 1. add action_dim, then adjust action_in_proj & action_out_proj
        # 2. add state dim & processing logic (could be selected):
        #    (1) ignore, just pass through
        #    (2) add to vlm backbones
        #    (3) add to action expert backbones
        #    (4) add to adarms conditioning
        # 2.5. pi05 (ours, minimal change from original pi05): by setting pi05=True & add state to vlm branch, we get trivial pi05 model.
        # 2.9. design config of tactile shape for different domains, generated by dataset(training) or set manually(deployment).
        # 3. create tactile encoder + expert branch
        super().__init__()
        self.config = config
        self.action_dim = config.action_dim
        # FTP1 uses pi05 mode (always uses adarms for action expert)
        self.pi05 = True

        paligemma_config = _gemma.get_config(config.paligemma_variant)  # default: 2b
        action_expert_config = _gemma.get_config(config.action_expert_variant)  # default: 300m
        tactile_expert_config = _gemma.get_config(config.tactile_expert_variant)

        # Conditionally create tactile encoder and expert branch.
        if config.use_tactile_input:
            self.hpt_tactile_encoder = FTP1HptTactileEncoder(config, token_dim=tactile_expert_config.width)
            model_use_tactile_expert = True
        else:
            self.hpt_tactile_encoder = None
            model_use_tactile_expert = False

        if not model_use_tactile_expert:
            tactile_expert_config = None
        self.use_tactile_expert_branch = model_use_tactile_expert

        self.paligemma_with_expert = FTP1PaliGemmaWithExpertModel(
            paligemma_config,
            action_expert_config,
            tactile_expert_config=tactile_expert_config,
            use_tactile_input=model_use_tactile_expert,
            use_adarms=[False, True],
            use_state_adarms_cond=(config.state_input_mode == "adarms"),
            precision=config.dtype,
        )

        self.state_input_mode = config.state_input_mode
        if self.state_input_mode == "none":
            pass
        elif self.state_input_mode == "vl_expert":
            self.state_encoder = FourierStateEncoder(config.action_dim, paligemma_config.width)
        elif self.state_input_mode in ["action_expert", "adarms"]:
            self.state_encoder = FourierStateEncoder(config.action_dim, action_expert_config.width)
        else:
            raise ValueError(
                f"Invalid state input mode: {self.state_input_mode}, should be one of ['none', 'vl_expert', 'action_expert', 'adarms']."
            )

        self.action_in_proj = nn.Linear(self.action_dim, action_expert_config.width)
        self.action_out_proj = nn.Linear(action_expert_config.width, self.action_dim)

        self.time_mlp_in = nn.Linear(action_expert_config.width, action_expert_config.width)
        self.time_mlp_out = nn.Linear(action_expert_config.width, action_expert_config.width)
        torch.set_float32_matmul_precision("high")
        # self.sample_actions = torch.compile(self.sample_actions, mode="max-autotune")

        # Initialize gradient checkpointing flag
        self.gradient_checkpointing_enabled = False
        self._flash_attn_infer_fallback_logged = False

        msg = "transformers_replace is not installed correctly. Please install it with `uv pip install transformers==4.53.2` and `cp -r ./src/openpi/models_pytorch/transformers_replace/* .venv/lib/python3.11/site-packages/transformers/`."
        try:
            from transformers.models.siglip import check

            if not check.check_whether_transformers_replace_is_installed_correctly():
                raise ValueError(msg)
        except ImportError:
            raise ValueError(msg) from None

    def gradient_checkpointing_enable(self):
        """Enable gradient checkpointing for memory optimization."""
        self.gradient_checkpointing_enabled = True
        self.paligemma_with_expert.paligemma.language_model.gradient_checkpointing = True
        self.paligemma_with_expert.paligemma.vision_tower.gradient_checkpointing = True
        self.paligemma_with_expert.gemma_expert.model.gradient_checkpointing = True
        if self.use_tactile_expert_branch and self.paligemma_with_expert.gemma_tactile_expert is not None:
            self.paligemma_with_expert.gemma_tactile_expert.model.gradient_checkpointing = True

        logging.info("Enabled gradient checkpointing for FTP1Pytorch model")

    def gradient_checkpointing_disable(self):
        """Disable gradient checkpointing."""
        self.gradient_checkpointing_enabled = False
        self.paligemma_with_expert.paligemma.language_model.gradient_checkpointing = False
        self.paligemma_with_expert.paligemma.vision_tower.gradient_checkpointing = False
        self.paligemma_with_expert.gemma_expert.model.gradient_checkpointing = False
        if self.use_tactile_expert_branch and self.paligemma_with_expert.gemma_tactile_expert is not None:
            self.paligemma_with_expert.gemma_tactile_expert.model.gradient_checkpointing = False

        logging.info("Disabled gradient checkpointing for FTP1Pytorch model")

    def is_gradient_checkpointing_enabled(self):
        """Check if gradient checkpointing is enabled."""
        return self.gradient_checkpointing_enabled

    def _apply_checkpoint(self, func, *args, **kwargs):
        """Helper method to apply gradient checkpointing if enabled."""
        if self.gradient_checkpointing_enabled and self.training:
            return torch.utils.checkpoint.checkpoint(
                func, *args, use_reentrant=False, preserve_rng_state=False, **kwargs
            )
        return func(*args, **kwargs)

    def _prepare_attention_masks_4d(self, att_2d_masks, *, dtype: torch.dtype):
        """Helper method to prepare 4D attention masks for transformer."""
        att_2d_masks_4d = att_2d_masks[:, None, :, :]
        zero = torch.zeros((), dtype=dtype, device=att_2d_masks_4d.device)
        neg_inf = torch.full((), torch.finfo(dtype).min, dtype=dtype, device=att_2d_masks_4d.device)
        return torch.where(att_2d_masks_4d, zero, neg_inf)

    def _get_action_adarms_dtype(self) -> torch.dtype:
        """Get dtype expected by action expert adaRMS conditioning projection."""
        input_layernorm = self.paligemma_with_expert.gemma_expert.model.layers[0].input_layernorm
        if hasattr(input_layernorm, "dense") and input_layernorm.dense is not None:
            return input_layernorm.dense.weight.dtype
        if hasattr(input_layernorm, "weight"):
            return input_layernorm.weight.dtype
        return torch.float32

    def _cast_action_adarms_cond(self, adarms_cond: Tensor | None) -> Tensor | None:
        if adarms_cond is None:
            return None
        target_dtype = self._get_action_adarms_dtype()
        if adarms_cond.dtype != target_dtype:
            adarms_cond = adarms_cond.to(dtype=target_dtype)
        return adarms_cond

    def _get_vlm_branch_dtype(self) -> torch.dtype:
        return self.paligemma_with_expert.paligemma.language_model.layers[0].self_attn.q_proj.weight.dtype

    def _get_action_branch_dtype(self) -> torch.dtype:
        return self.paligemma_with_expert.gemma_expert.model.layers[0].self_attn.q_proj.weight.dtype

    def _get_tactile_branch_dtype(self) -> torch.dtype:
        if self.use_tactile_expert_branch and self.paligemma_with_expert.gemma_tactile_expert is not None:
            return self.paligemma_with_expert.gemma_tactile_expert.model.layers[0].self_attn.q_proj.weight.dtype
        return self._get_action_branch_dtype()


    def _resolve_attn_implementation(self, *, for_inference: bool) -> str:
        attn_impl = str(getattr(self.config, "attn_implementation", "eager"))
        if for_inference and attn_impl == "flash_attention_2":
            if not self._flash_attn_infer_fallback_logged:
                logging.warning(
                    "FTP1 sample_actions falls back to eager attention when model.attn_implementation=flash_attention_2 to keep validation stable."
                )
                self._flash_attn_infer_fallback_logged = True
            return "eager"
        return attn_impl

    def _forward_action_branch_full(
        self,
        prefix_embs: Tensor,
        prefix_pad_masks: Tensor,
        suffix_embs: Tensor,
        suffix_pad_masks: Tensor,
        suffix_att_masks: Tensor,
        adarms_cond: Tensor | None,
        *,
        action_active_tail_tokens: int,
        tactile_embs: Tensor | None = None,
        tactile_pad_masks: Tensor | None = None,
        attn_implementation: str | None = None,
    ) -> Tensor:
        if (
            self.paligemma_with_expert.paligemma.language_model.layers[0].self_attn.q_proj.weight.dtype
            == torch.bfloat16
        ):
            prefix_embs = prefix_embs.to(dtype=torch.bfloat16)
            suffix_embs = suffix_embs.to(dtype=torch.bfloat16)
            if tactile_embs is not None:
                tactile_embs = tactile_embs.to(dtype=torch.bfloat16)

        attn_impl = attn_implementation or self._resolve_attn_implementation(for_inference=False)
        self.paligemma_with_expert.paligemma.language_model.config._attn_implementation = attn_impl  # noqa: SLF001
        self.paligemma_with_expert.gemma_expert.model.config._attn_implementation = attn_impl  # noqa: SLF001
        if self.use_tactile_expert_branch and self.paligemma_with_expert.gemma_tactile_expert is not None:
            self.paligemma_with_expert.gemma_tactile_expert.model.config._attn_implementation = attn_impl  # noqa: SLF001

        expert_layout = build_expert_attention_layout(
            prefix_pad_masks,
            suffix_pad_masks,
            suffix_att_masks,
            tactile_pad_masks=tactile_pad_masks,
        )
        att_2d_masks_4d = self._prepare_attention_masks_4d(
            expert_layout.att_2d_masks,
            dtype=self._get_action_branch_dtype(),
        )

        if tactile_embs is not None:
            outputs, _ = self.paligemma_with_expert.forward(
                attention_mask=att_2d_masks_4d,
                position_ids=expert_layout.position_ids,
                past_key_values=None,
                inputs_embeds=[prefix_embs, tactile_embs, suffix_embs],
                use_cache=False,
                adarms_cond=[None, None, adarms_cond],
                adarms_active_tail_tokens=[None, None, action_active_tail_tokens],
            )
            return outputs[2]

        outputs, _ = self.paligemma_with_expert.forward(
            attention_mask=att_2d_masks_4d,
            position_ids=expert_layout.position_ids,
            past_key_values=None,
            inputs_embeds=[prefix_embs, suffix_embs],
            use_cache=False,
            adarms_cond=[None, adarms_cond],
            adarms_active_tail_tokens=[None, action_active_tail_tokens],
        )
        return outputs[1]

    def _preprocess_observation(self, observation, *, train=True):
        """Helper method to preprocess observation."""
        # images, img_masks, lang_tokens, lang_masks, state, tactiles, tactile_function_areas, domain_names
        observation = _preprocessing.preprocess_observation_pytorch(observation, train=train, image_keys=None)
        action_masks = observation.action_masks
        if action_masks is not None and action_masks.dtype != torch.bool:
            action_masks = action_masks > 0
        return (
            list(observation.images.values()),
            list(observation.image_masks.values()),
            observation.tokenized_prompt,
            observation.tokenized_prompt_mask,
            observation.state,
            observation.state_masks,
            observation.tactiles if hasattr(observation, "tactiles") and observation.tactiles is not None else None,
            observation.tactile_function_areas
            if hasattr(observation, "tactile_function_areas") and observation.tactile_function_areas is not None
            else None,
            observation.tactile_sensors
            if hasattr(observation, "tactile_sensors") and observation.tactile_sensors is not None
            else None,
            observation.domain_names
            if hasattr(observation, "domain_names") and observation.domain_names is not None
            else None,
            action_masks,
        )

    def _encode_state_tokens(self, state: Tensor, state_masks: Tensor | None) -> tuple[Tensor, Tensor, Tensor, Tensor]:
        state_embs_raw = self.state_encoder(state)
        if state_masks is None:
            state_pad_masks = torch.ones(state.shape[0], state.shape[1], dtype=torch.bool, device=state.device)
        else:
            state_pad_masks = state_masks.to(dtype=torch.bool, device=state.device)
        state_att_masks = torch.zeros(state_pad_masks.shape, dtype=torch.bool, device=state.device)
        state_embs = state_embs_raw * state_pad_masks.unsqueeze(-1).to(dtype=state_embs_raw.dtype)
        return state_embs_raw, state_embs, state_pad_masks, state_att_masks

    def _build_adarms_cond_from_state(self, state_embs_raw: Tensor, adarms_cond: Tensor) -> Tensor:
        state_emb_mean = state_embs_raw.mean(dim=1)
        state_emb_mean = nn.functional.layer_norm(
            state_emb_mean,
            normalized_shape=(state_emb_mean.shape[-1],),
        )
        adarms_cond_norm = nn.functional.layer_norm(
            adarms_cond,
            normalized_shape=(adarms_cond.shape[-1],),
        )
        return torch.cat([state_emb_mean, adarms_cond_norm], dim=-1)

    def sample_noise(self, shape, device):
        return torch.normal(
            mean=0.0,
            std=1.0,
            size=shape,
            dtype=torch.float32,
            device=device,
        )

    def sample_time(self, bsize, device):
        time_beta = sample_beta(1.5, 1.0, bsize, device)
        time = time_beta * 0.999 + 0.001
        return time.to(dtype=torch.float32, device=device)

    def embed_prefix(self, images, img_masks, lang_tokens, lang_masks) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        """Embed images with SigLIP and language tokens with embedding layer to prepare
        for PaliGemma transformer processing.
        """
        embs = []
        pad_masks = []
        att_masks = []

        # Process images
        for img, img_mask in zip(images, img_masks, strict=True):  # List[(B, C, H, W)], List[(B, )]

            def image_embed_func(img):
                return self.paligemma_with_expert.embed_image(img)

            img_emb = self._apply_checkpoint(image_embed_func, img)  # (B, 16*16, 2048)

            bsize, num_img_embs = img_emb.shape[:2]

            # Cache the number of tokens per image (all images have the same count after resize)
            if not hasattr(self, "_image_tokens_per_image") or self._image_tokens_per_image is None:
                self._image_tokens_per_image = num_img_embs

            embs.append(img_emb)
            pad_masks.append(img_mask[:, None].expand(bsize, num_img_embs))  # (B, ) --> (B, 14x14)

            # Create attention masks so that image tokens attend to each other
            att_masks += [0] * num_img_embs

        # Process language tokens
        def lang_embed_func(lang_tokens):
            lang_emb = self.paligemma_with_expert.embed_language_tokens(lang_tokens)
            lang_emb_dim = lang_emb.shape[-1]
            return lang_emb * math.sqrt(lang_emb_dim)

        lang_emb = self._apply_checkpoint(lang_embed_func, lang_tokens)

        embs.append(lang_emb)
        pad_masks.append(lang_masks)

        # full attention between image and language inputs
        num_lang_embs = lang_emb.shape[1]
        att_masks += [0] * num_lang_embs

        embs = torch.cat(embs, dim=1)
        pad_masks = torch.cat(pad_masks, dim=1)
        att_masks = torch.tensor(att_masks, dtype=torch.bool, device=pad_masks.device)  # (N, )

        # Get batch size from the first dimension of the concatenated tensors
        bsize = pad_masks.shape[0]
        att_masks = att_masks[None, :].expand(bsize, len(att_masks))  # (B, N)

        return embs, pad_masks, att_masks  # (B, N, D), (B, N), (B, N)

    def embed_suffix(self, noisy_actions, timestep):
        """Embed state, noisy_actions, timestep to prepare for Expert Gemma processing."""
        embs = []
        pad_masks = []
        att_masks = []

        # Embed timestep using sine-cosine positional encoding with sensitivity in the range [0, 1]
        # self.action_in_proj.in_features = 32, self.action_in_proj.out_features = action_expert_config.width
        time_emb = create_sinusoidal_pos_embedding(
            timestep, self.action_in_proj.out_features, min_period=4e-3, max_period=4.0, device=timestep.device
        )  # (B, 1024)
        time_emb = time_emb.type(dtype=timestep.dtype)

        # Fuse timestep + action information using an MLP
        def action_proj_func(noisy_actions):
            return self.action_in_proj(noisy_actions)  # (B, T, 32) --> (B, T, 1024)

        action_emb = self._apply_checkpoint(action_proj_func, noisy_actions)

        # time MLP (for adaRMS)
        def time_mlp_func(time_emb):
            x = self.time_mlp_in(time_emb)  # (B, 1024) --> (B, 1024)
            x = F.silu(x)  # swish == silu
            x = self.time_mlp_out(x)  # (B, 1024) --> (B, 1024)
            return F.silu(x)  # (B, 1024) --> (B, 1024)

        time_emb = self._apply_checkpoint(time_mlp_func, time_emb)
        action_time_emb = action_emb  # (B, T, 1024)
        adarms_cond = time_emb  # (B, 1024)

        # Add to input tokens
        embs.append(action_time_emb)

        # embs = [T action tokens], timestamp is an independent adarms_cond token (timestamps transformed through 1 MLP)

        bsize, action_time_dim = action_time_emb.shape[:2]
        action_time_mask = torch.ones(bsize, action_time_dim, dtype=torch.bool, device=timestep.device)
        pad_masks.append(action_time_mask)

        # Set attention masks so that image, language and state inputs do not attend to action tokens
        att_masks += [1] + ([0] * (self.config.action_horizon - 1))

        embs = torch.cat(embs, dim=1)
        pad_masks = torch.cat(pad_masks, dim=1)
        att_masks = torch.tensor(att_masks, dtype=torch.bool, device=embs.device)
        att_masks = att_masks[None, :].expand(bsize, len(att_masks))  # (1, N) --> (B, N)

        return embs, pad_masks, att_masks, adarms_cond  # (B, N, D), (B, N), (B, N), (B, 1024)

    def embed_tactile(self, tactiles, tactile_function_areas, tactile_sensors):
        """Embed tactile inputs using FTP1HptTactileEncoder."""
        if (
            not self.config.use_tactile_input
            or self.hpt_tactile_encoder is None
            or tactiles is None
            or tactile_function_areas is None
            or tactile_sensors is None
        ):
            return None, None

        def tactile_embed_func(tactiles, tactile_function_areas, tactile_sensors):
            tactile_embs, tactile_pad_masks = self.hpt_tactile_encoder(
                tactiles, tactile_function_areas, tactile_sensors
            )
            return tactile_embs, tactile_pad_masks

        tactile_embs, tactile_pad_masks = self._apply_checkpoint(
            tactile_embed_func, tactiles, tactile_function_areas, tactile_sensors
        )

        if tactile_embs is None:
            return None, None
        return tactile_embs, tactile_pad_masks

    def forward(self, observation, actions, noise=None, time=None) -> Tensor:
        """Do a full training forward pass and compute the loss (batch_size x num_steps x num_motors)"""

        (
            images,
            img_masks,
            lang_tokens,
            lang_masks,
            state,
            state_masks,
            tactiles,
            tactile_function_areas,
            tactile_sensors,
            domain_names,
            action_masks,
        ) = self._preprocess_observation(observation, train=True)

        if actions.shape[-1] != self.action_dim:
            raise ValueError(
                f"Action dim mismatch: batch actions last dim is {actions.shape[-1]}, "
                f"but model.action_dim is {self.action_dim}. "
                "Please align dataset output dim with model config."
            )
        if action_masks is not None and action_masks.shape[-1] != self.action_dim:
            raise ValueError(
                f"Action-mask dim mismatch: action_mask last dim is {action_masks.shape[-1]}, "
                f"but model.action_dim is {self.action_dim}. "
                "Please align dataset output dim with model config."
            )

        if noise is None:
            noise = self.sample_noise(actions.shape, actions.device)  # (B, T, D)

        if time is None:
            time = self.sample_time(actions.shape[0], actions.device)  # (B, )

        time_expanded = time[:, None, None]  # (B, 1, 1)
        x_t = time_expanded * noise + (1 - time_expanded) * actions
        u_t = noise - actions

        prefix_embs, prefix_pad_masks, prefix_att_masks = self.embed_prefix(images, img_masks, lang_tokens, lang_masks)
        suffix_embs, suffix_pad_masks, suffix_att_masks, adarms_cond = self.embed_suffix(
            x_t, time
        )  # dim=1024 for 300m gemma
        tactile_embs, tactile_pad_masks = self.embed_tactile(tactiles, tactile_function_areas, tactile_sensors)
        if self.config.use_tactile_input and tactile_embs is None:
            raise ValueError(
                "self.config.use_tactile_input=True, requires valid tactile inputs, but tactile embeddings are None."
            )

        if self.state_input_mode != "none":
            state_embs_raw, state_embs, state_pad_masks, state_att_masks = self._encode_state_tokens(state, state_masks)
        else:
            pass

        if self.state_input_mode == "vl_expert":
            prefix_embs = torch.cat([state_embs, prefix_embs], dim=1)
            prefix_pad_masks = torch.cat([state_pad_masks, prefix_pad_masks], dim=1)
            prefix_att_masks = torch.cat([state_att_masks, prefix_att_masks], dim=1)
        elif self.state_input_mode == "action_expert":
            suffix_embs = torch.cat([state_embs, suffix_embs], dim=1)
            suffix_pad_masks = torch.cat([state_pad_masks, suffix_pad_masks], dim=1)
            suffix_att_masks = torch.cat([state_att_masks, suffix_att_masks], dim=1)
        elif self.state_input_mode == "adarms":
            adarms_cond = self._build_adarms_cond_from_state(state_embs_raw, adarms_cond)
        else:
            pass

        # Current FTP1 action branch:
        # - suffix_embs are action tokens (+ optional state tokens for state_input_mode='action_expert'),
        # - timestep is injected via adarms_cond (not an explicit suffix token).
        action_active_tail_tokens = min(self.config.action_horizon, suffix_pad_masks.shape[1])
        adarms_cond = self._cast_action_adarms_cond(adarms_cond)
        action_out = self._forward_action_branch_full(
            prefix_embs,
            prefix_pad_masks,
            suffix_embs,
            suffix_pad_masks,
            suffix_att_masks,
            adarms_cond,
            action_active_tail_tokens=action_active_tail_tokens,
            tactile_embs=tactile_embs if self.use_tactile_expert_branch else None,
            tactile_pad_masks=tactile_pad_masks if self.use_tactile_expert_branch else None,
            attn_implementation=self._resolve_attn_implementation(for_inference=False),
        )

        action_out = action_out[:, -self.config.action_horizon :]
        action_out = action_out.to(dtype=torch.float32)

        # Apply gradient checkpointing to final action projection if enabled
        def action_out_proj_func(action_out):
            return self.action_out_proj(action_out)  # (B, T, self.action_dim), self.action_dim is set in the confifg

        v_t = self._apply_checkpoint(action_out_proj_func, action_out)

        if action_masks is not None:
            loss_per_element = F.mse_loss(u_t, v_t, reduction="none")
            loss = loss_per_element * action_masks
            mask_sum = action_masks.sum().clamp(min=1)
            loss = loss.sum() / mask_sum
        else:
            loss = F.mse_loss(u_t, v_t, reduction="none").mean()

        return {"loss": loss}

    @torch.no_grad()
    def sample_actions(self, device, observation, noise=None, num_steps=10) -> Tensor:
        """Do a full inference forward and compute the action (batch_size x num_steps x num_motors)"""

        bsize = observation.state.shape[0]
        if noise is None:
            actions_shape = (bsize, self.config.action_horizon, self.config.action_dim)
            noise = self.sample_noise(actions_shape, device)

        (
            images,
            img_masks,
            lang_tokens,
            lang_masks,
            state,
            state_masks,
            tactiles,
            tactile_function_areas,
            tactile_sensors,
            domain_names,
            action_masks,
        ) = self._preprocess_observation(observation, train=False)

        # get tactile embeddings + masks
        if self.config.use_tactile_input:
            tactile_embs, tactile_pad_masks = self.embed_tactile(tactiles, tactile_function_areas, tactile_sensors)
        else:
            tactile_embs, tactile_pad_masks = None, None
        if self.config.use_tactile_input and tactile_embs is None:
            raise ValueError(
                "self.config.use_tactile_input=True, requires valid tactile inputs, but tactile embeddings are None."
            )
        tactile_pack = (tactile_embs, tactile_pad_masks) if tactile_pad_masks is not None else None
        cached_static_suffix_pad_masks = None

        # get prefix embs, masks & position ids (vlm branch cache)
        prefix_embs, prefix_pad_masks, prefix_att_masks = self.embed_prefix(images, img_masks, lang_tokens, lang_masks)

        if self.state_input_mode != "none":
            state_embs_raw, state_embs, state_pad_masks, state_att_masks = self._encode_state_tokens(state, state_masks)
            state_embs_pack = (state_embs_raw, state_embs, state_pad_masks, state_att_masks)
        else:
            state_embs_pack = None
        if self.state_input_mode == "vl_expert":
            prefix_embs = torch.cat([state_embs, prefix_embs], dim=1)
            prefix_pad_masks = torch.cat([state_pad_masks, prefix_pad_masks], dim=1)
            prefix_att_masks = torch.cat([state_att_masks, prefix_att_masks], dim=1)
        past_key_values = None
        attn_impl = self._resolve_attn_implementation(for_inference=True)
        self.paligemma_with_expert.paligemma.language_model.config._attn_implementation = attn_impl  # noqa: SLF001
        self.paligemma_with_expert.gemma_expert.model.config._attn_implementation = attn_impl  # noqa: SLF001
        if self.use_tactile_expert_branch and tactile_embs is not None:
            assert self.paligemma_with_expert.gemma_tactile_expert is not None
            self.paligemma_with_expert.gemma_tactile_expert.model.config._attn_implementation = attn_impl  # noqa: SLF001

        prefix_layout = build_prefix_attention_layout(prefix_pad_masks, prefix_att_masks)
        prefix_att_2d_masks_4d = self._prepare_attention_masks_4d(
            prefix_layout.att_2d_masks,
            dtype=self._get_vlm_branch_dtype(),
        )
        if self.use_tactile_expert_branch and tactile_embs is not None:
            tactile_branch_dtype = self._get_tactile_branch_dtype()
            if tactile_embs.dtype != tactile_branch_dtype:
                tactile_embs = tactile_embs.to(dtype=tactile_branch_dtype)

            tactile_layout = build_tactile_attention_layout(
                tactile_pad_masks,
                position_offset=prefix_layout.position_ids[:, -1:] + 1,
            )

            # Cache VLM tokens first.
            _, vlm_past_key_values = self.paligemma_with_expert.forward(
                attention_mask=prefix_att_2d_masks_4d,
                position_ids=prefix_layout.position_ids,
                past_key_values=None,
                inputs_embeds=[prefix_embs, None, None],
                use_cache=True,
            )

            # Then cache tactile tokens and merge both caches.
            tactile_att_2d_masks_4d = self._prepare_attention_masks_4d(
                tactile_layout.att_2d_masks,
                dtype=tactile_branch_dtype,
            )
            _, tactile_past_key_values = self.paligemma_with_expert.forward(
                attention_mask=tactile_att_2d_masks_4d,
                position_ids=tactile_layout.position_ids,
                past_key_values=None,
                inputs_embeds=[None, tactile_embs, None],
                use_cache=True,
            )

            combined_past_key_values = DynamicCache()
            num_layers = len(vlm_past_key_values)
            for layer_idx in range(num_layers):
                vlm_kv = vlm_past_key_values[layer_idx]
                tactile_kv = tactile_past_key_values[layer_idx]
                combined_past_key_values.update(
                    torch.cat([vlm_kv[0], tactile_kv[0]], dim=2),
                    torch.cat([vlm_kv[1], tactile_kv[1]], dim=2),
                    layer_idx,
                )
            past_key_values = combined_past_key_values
        else:
            _, past_key_values = self.paligemma_with_expert.forward(
                attention_mask=prefix_att_2d_masks_4d,
                position_ids=prefix_layout.position_ids,
                past_key_values=None,
                inputs_embeds=[prefix_embs, None],
                use_cache=True,
            )

        dt = -1.0 / num_steps
        dt = torch.tensor(dt, dtype=torch.float32, device=device)

        x_t = noise
        time = torch.tensor(1.0, dtype=torch.float32, device=device)
        while time >= -dt / 2:
            expanded_time = time.expand(bsize)

            v_t = self.denoise_step(
                prefix_pad_masks,
                past_key_values,
                x_t,
                expanded_time,
                prefix_embs=prefix_embs,
                tactile_pack=tactile_pack,
                state_embs_pack=state_embs_pack,
                cached_static_suffix_pad_masks=cached_static_suffix_pad_masks,
                attn_implementation=attn_impl,
            )

            # Euler step - use new tensor assignment instead of in-place operation
            x_t = x_t + dt * v_t
            time += dt
        return x_t

    def denoise_step(
        self,
        prefix_pad_masks,
        past_key_values,
        x_t,
        timestep,
        prefix_embs=None,
        tactile_pack=None,
        state_embs_pack=None,
        cached_static_suffix_pad_masks=None,
        attn_implementation: str | None = None,
    ):
        """Apply one denoising step of the noise `x_t` at a given timestep."""
        suffix_embs, suffix_pad_masks, suffix_att_masks, adarms_cond = self.embed_suffix(x_t, timestep)
        use_cached_static_suffix = False

        if state_embs_pack is not None:
            state_embs_raw, state_embs, state_pad_masks, state_att_masks = state_embs_pack
        if self.state_input_mode == "action_expert":
            assert state_embs_pack is not None
            if not use_cached_static_suffix:
                suffix_embs = torch.cat([state_embs, suffix_embs], dim=1)
                suffix_pad_masks = torch.cat([state_pad_masks, suffix_pad_masks], dim=1)
                suffix_att_masks = torch.cat([state_att_masks, suffix_att_masks], dim=1)
        elif self.state_input_mode == "adarms":
            assert state_embs_pack is not None
            adarms_cond = self._build_adarms_cond_from_state(state_embs_raw, adarms_cond)
        else:
            pass

        action_active_tail_tokens = min(self.config.action_horizon, suffix_pad_masks.shape[1])
        adarms_cond = self._cast_action_adarms_cond(adarms_cond)
        attn_impl = attn_implementation or self._resolve_attn_implementation(for_inference=False)

        if self.use_tactile_expert_branch:
            tactile_pad_masks = tactile_pack[1] if tactile_pack is not None else None
            denoise_layout = build_action_denoise_layout(
                prefix_pad_masks,
                suffix_pad_masks,
                suffix_att_masks,
                tactile_pad_masks=tactile_pad_masks,
            )
            full_att_2d_masks_4d = self._prepare_attention_masks_4d(
                denoise_layout.att_2d_masks,
                dtype=self._get_action_branch_dtype(),
            )
            self.paligemma_with_expert.gemma_expert.model.config._attn_implementation = attn_impl  # noqa: SLF001

            if tactile_pad_masks is not None:
                outputs_embeds, _ = self.paligemma_with_expert.forward(
                    attention_mask=full_att_2d_masks_4d,
                    position_ids=denoise_layout.position_ids,
                    past_key_values=past_key_values,
                    inputs_embeds=[None, None, suffix_embs],
                    use_cache=False,
                    adarms_cond=[None, None, adarms_cond],
                    adarms_active_tail_tokens=[None, None, action_active_tail_tokens],
                )
                action_out = outputs_embeds[2]
            else:
                outputs_embeds, _ = self.paligemma_with_expert.forward(
                    attention_mask=full_att_2d_masks_4d,
                    position_ids=denoise_layout.position_ids,
                    past_key_values=past_key_values,
                    inputs_embeds=[None, suffix_embs],
                    use_cache=False,
                    adarms_cond=[None, adarms_cond],
                    adarms_active_tail_tokens=[None, action_active_tail_tokens],
                )
                action_out = outputs_embeds[1]
        else:
            denoise_layout = build_action_denoise_layout(
                prefix_pad_masks,
                suffix_pad_masks,
                suffix_att_masks,
                cached_static_suffix_pad_masks=cached_static_suffix_pad_masks if use_cached_static_suffix else None,
            )
            full_att_2d_masks_4d = self._prepare_attention_masks_4d(
                denoise_layout.att_2d_masks,
                dtype=self._get_action_branch_dtype(),
            )
            self.paligemma_with_expert.gemma_expert.model.config._attn_implementation = attn_impl  # noqa: SLF001
            outputs_embeds, _ = self.paligemma_with_expert.forward(
                attention_mask=full_att_2d_masks_4d,
                position_ids=denoise_layout.position_ids,
                past_key_values=past_key_values,
                inputs_embeds=[None, suffix_embs],
                use_cache=False,
                adarms_cond=[None, adarms_cond],
                adarms_active_tail_tokens=[None, action_active_tail_tokens],
            )
            action_out = outputs_embeds[1]

        action_out = action_out[:, -self.config.action_horizon :]
        action_out = action_out.to(dtype=torch.float32)
        return self.action_out_proj(action_out)
